export const baseStorage = [
    {
        id: 1,
        color: '#1943AE',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 20,
        temperatureId: 1,
        zoneId: 1,
        temperature: '-20',
        zone: 'Zone A',
    },
    {
        id: 2,
        color: '#1943AE',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 20,
        temperatureId: 2,
        zoneId: 3,
        temperature: '-80',
        zone: 'Zone C',
    },
    {
        id: 3,
        color: '#FA6363',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 20,
        temperatureId: 2,
        zoneId: 1,
        temperature: '-80',
        zone: 'Zone A',
    },
    {
        id: 4,
        color: '#1943AE',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 20,
        temperatureId: 3,
        zoneId: 1,
        temperature: 'LN2',
        zone: 'Zone A',
    },
    {
        id: 5,
        color: '#FA6363',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 20,
        temperatureId: 1,
        zoneId: 2,
        temperature: '-20',
        zone: 'Zone B',
    },
    {
        id: 6,
        color: '#1943AE',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 20,
        temperatureId: 2,
        zoneId: 2,
        temperature: '-80',
        zone: 'Zone B',
    },
    {
        id: 7,
        color: '#FA6363',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 20,
        temperatureId: 3,
        zoneId: 2,
        temperature: 'LN2',
        zone: 'Zone B',
    },
    {
        id: 8,
        color: '#1943AE',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 14,
        temperatureId: 2,
        zoneId: 1,
        temperature: '-80',
        zone: 'Zone A',
    },
    {
        id: 9,
        color: '#FA6363',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 11,
        temperatureId: 3,
        zoneId: 1,
        temperature: 'LN2',
        zone: 'Zone A',
    },
    {
        id: 10,
        color: '#1943AE',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 18,
        temperatureId: 2,
        zoneId: 2,
        temperature: '-80',
        zone: 'Zone B',
    },
    {
        id: 11,
        color: '#FA6363',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 8,
        temperatureId: 1,
        zoneId: 1,
        temperature: '-20',
        zone: 'Zone A',
    },
    {
        id: 12,
        color: '#1943AE',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 16,
        temperatureId: 2,
        zoneId: 3,
        temperature: '-80',
        zone: 'Zone C',
    },
    {
        id: 13,
        color: '#FA6363',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 18,
        temperatureId: 2,
        zoneId: 2,
        temperature: '-80',
        zone: 'Zone B',
    },
    {
        id: 14,
        color: '#1943AE',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 14,
        temperatureId: 3,
        zoneId: 1,
        temperature: 'LN2',
        zone: 'Zone A',
    },
    {
        id: 15,
        color: '#FA6363',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 14,
        temperatureId: 2,
        zoneId: 1,
        temperature: '-80',
        zone: 'Zone A',
    },
    {
        id: 16,
        color: '#1943AE',
        title: 'Freezer Atara 001',
        location: 'Storage Suite 3, Germany - Cellfuse',
        quantity: 14,
        temperatureId: 2,
        zoneId: 1,
        temperature: '-80',
        zone: 'Zone A',
    },
]